# Generated by Django 6.0.4 on 2026-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
