# Generated by Django 6.0.4 on 2026-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_useraccount_qualification_useraccount_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='specialized_subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
