# Generated by Django 6.0.6 on 2026-07-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_routine_academic_year_routine_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_department',
            field=models.CharField(default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_semester',
            field=models.CharField(default='All', max_length=50),
        ),
    ]
