# Generated by Django 6.0.6 on 2026-07-23 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notice_target_department_notice_target_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(default='Computer Science & Technology', max_length=100)),
                ('semester', models.CharField(default='5th Semester', max_length=50)),
                ('shift', models.CharField(default='1st Shift', max_length=50)),
                ('total_marks', models.IntegerField(default=100)),
                ('due_date', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('drive_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('drive_link', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('marks_obtained', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Submitted', max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.assignment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
