# Generated by Django 6.0.4 on 2026-07-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_useraccount_group_classrepresentative_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrepresentative',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
