# Generated by Django 6.0.4 on 2026-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
