# Generated by Django 6.0.4 on 2026-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_useraccount_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
