# Generated by Django 6.0.4 on 2026-04-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_useraccount_specialized_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='assigned_classes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
