# Generated by Django 6.0.4 on 2026-04-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_useraccount_assigned_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
