# Generated by Django 6.0.4 on 2026-04-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_useraccount_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
