# Generated by Django 6.0.4 on 2026-07-23 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notice_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='routine',
            name='department',
            field=models.CharField(default='Computer Science & Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='routine',
            name='end_time',
            field=models.CharField(default='08:45', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='section',
            field=models.CharField(blank=True, default='A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='semester',
            field=models.CharField(default='1st Semester', max_length=50),
        ),
        migrations.AddField(
            model_name='routine',
            name='session',
            field=models.CharField(default='2023-24', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='shift',
            field=models.CharField(default='1st Shift', max_length=50),
        ),
        migrations.AddField(
            model_name='routine',
            name='start_time',
            field=models.CharField(default='08:00', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='teacher_initials',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='room',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='routine',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraccount'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RoutineFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='routine_files/')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraccount')),
            ],
        ),
    ]
